apiVersion: machinelearning.seldon.io/v2
kind: SeldonDeployment
metadata:
  name: tennis-model
  namespace: seldon
spec:
  name: tennis
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: leochen66/sklearn_tennis:1.2
    graph:
      name: classifier
    name: default
    replicas: 1